In [19]:
import pandas as pd
import numpy as np

In [ ]:
import zipfile
with zipfile.ZipFile('../data/raw/Archive.zip', 'r') as zip_ref:
    zip_ref.extractall('../data/raw')

In [20]:
df_orders = pd.read_csv('../data/raw/orders.csv')

In [21]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [22]:
print(df_orders.columns)
print(df_orders.shape)

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

In [ ]:
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')

In [27]:

print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [29]:
df_products = pd.read_csv('/data/raw/products.csv')
print(df_products.columns)
print(df_products.shape)
df_products.head()

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices'], dtype='str')
(49693, 5)

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [30]:
df_departments = pd.read_csv('../data/raw/departments_t.csv')

In [31]:
print(df_departments.columns)
print(df_departments.shape)

df_departments.head()

Index(['department_id', 'department'], dtype='str')
(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [32]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')

In [33]:
print(df_aisles.columns)
print(df_aisles.shape)

df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [34]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [35]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [36]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [37]:
pd.options.display.float_format = '{:,.2f}'.format

In [40]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [41]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [46]:
df_orders['order_id'].nunique()

3421083

In [51]:
df_orders['eval_set'].value_counts(dropna = False)

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [55]:
df_orders['order_dow'].value_counts().sort_index()

order_dow
0    600905
1    587478
2    467260
3    436972
4    426339
5    453368
6    448761
Name: count, dtype: int64

In [57]:
df_orders['order_hour_of_day'].value_counts().sort_index()

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

In [58]:
df_orders['days_since_prior_order'].isna().sum()

np.int64(206209)

In [59]:
df_orders['order_id'].is_unique

True

In [62]:
df_orders['order_dow'].between(0, 6).all()

np.True_

In [63]:
df_orders['order_hour_of_day'].between(0, 23).all()

np.True_

In [64]:
df_orders_train = df_orders[df_orders['eval_set'] == 'train']

In [68]:
df_orders_train.drop(columns=['eval_set'], inplace= True)
df_orders_train.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,11,4,8,14.00
25,1492625,2,15,1,11,30.00
49,2196797,5,5,0,11,6.00
74,525192,7,21,2,11,6.00
78,880375,8,4,1,14,10.00

In [70]:
df_orders_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [72]:
df_orders_products_train.dtypes

order_id             int64
product_id           int64
add_to_cart_order    int64
reordered            int64
dtype: object

In [75]:
df_orders_products_train.isna().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [76]:
# Q1: How many line items exist?
len(df_orders_products_train)

1384617

In [77]:
# Q2: How many unique orders are represented in this table?
df_orders_products_train['order_id'].nunique()

131209

In [78]:
# Q3: How many unique products are represented in this table?
df_orders_products_train['product_id'].nunique()

39123

In [80]:
# Q4: Exploring reorder behavior
df_orders_products_train['reordered'].value_counts(dropna=False)

reordered
1    828824
0    555793
Name: count, dtype: int64

In [82]:
# Q5: Reorder share
df_orders_products_train['reordered'].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

In [84]:
# Q6: Understanding add_to_cart_order
df_orders_products_train['add_to_cart_order'].describe()

count   1,384,617.00
mean            8.76
std             7.42
min             1.00
25%             3.00
50%             7.00
75%            12.00
max            80.00
Name: add_to_cart_order, dtype: float64

In [87]:
# Q7: Which cart positions appear most often?
df_orders_products_train['add_to_cart_order'].value_counts().sort_index().head(20)

add_to_cart_order
1     131209
2     124364
3     116996
4     108963
5     100745
6      91850
7      83142
8      74601
9      66618
10     59401
11     52848
12     46814
13     41431
14     36588
15     32194
16     28363
17     24841
18     21733
19     19014
20     16541
Name: count, dtype: int64

In [93]:
(df_orders_products_train['add_to_cart_order'] > 0).all()

np.True_

In [95]:
df_orders_products_train[['order_id', 'product_id']]

         order_id  product_id
0               1       49302
1               1       11109
2               1       10246
3               1       49683
4               1       43633
...           ...         ...
1384612   3421063       14233
1384613   3421063       35548
1384614   3421070       35951
1384615   3421070       16953
1384616   3421070        4724

[1384617 rows x 2 columns]

In [98]:
df_products.dtypes

product_id         int64
product_name         str
aisle_id           int64
department_id      int64
prices           float64
dtype: object

In [105]:
# Q1: How many unique products exist?
df_products['product_id'].nunique()

49686

In [107]:
# Q2: Are product IDs unique?
df_products['product_id'].is_unique

False

In [108]:
# Q3: How many unique departments are referenced in the product table?
df_products['department_id'].nunique()

21

In [109]:
# Q4: How many unique aisles are referenced in the product table?
df_products['aisle_id'].nunique()

134

In [120]:
# Q5: Do some product names repeat?
df_products['product_name'].duplicated().any()

np.True_

In [121]:
df_departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [122]:
df_departments.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     str
dtypes: int64(1), str(1)
memory usage: 468.0 bytes

In [123]:
df_departments.dtypes

department_id    int64
department         str
dtype: object

In [124]:
df_departments.isna().sum()

department_id    0
department       0
dtype: int64

In [125]:
# Q1: How many departments exist?
df_departments["department"].nunique()

21

In [126]:
# Q2: Are department_id values unique?
df_departments['department_id'].is_unique

True

In [129]:
# Q3: Are there missing values in the table?
df_departments.isna().all()

department_id    False
department       False
dtype: bool

In [130]:
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [132]:
df_aisles.isna().sum()

aisle_id    0
aisle       0
dtype: int64

In [134]:
# Q1: How many aisles exist?
df_aisles['aisle_id'].value_counts().sum()

np.int64(134)

In [135]:
df_aisles['aisle_id'].nunique()

134

In [136]:
# Q2: Are aisle_id values unique?
df_aisles['aisle_id'].is_unique

True

In [137]:
# Q3: Are there missing values in the table?
df_aisles.isna().sum()

aisle_id    0
aisle       0
dtype: int64