In [2]:
import pandas as pd

In [12]:
df_products = pd.read_csv('../data/raw/products.csv')
df_departments = pd.read_csv('../data/raw/departments_t.csv')
df_orders = pd.read_csv('../data/raw/orders.csv')

In [13]:
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on= 'department_id',
    how= 'left',
)

In [42]:
# Homework P1: Questions unlocked after the first merge
# How many products belong to each department?

df_products_departments['department'].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [43]:
# Which departments contain the most products?
# as this method() also sorts the series, we can get the first 3 lets say
df_products_departments['department'].value_counts().head(3)

department
personal care    6565
snacks           6264
pantry           5371
Name: count, dtype: int64

In [44]:
# Are products concentrated in a small number of departments?
df_norm = df_products_departments['department'].value_counts(normalize=True)
df_norm.head()
# ինչպես տեսնում ենք առաջին 5-ը 50%ից ավելիէ , հետևաբար կարող ենք ասել, որ առաջին հինգ department-ում է կենտրոնացած

department
personal care    0.132111
snacks           0.126054
pantry           0.108084
beverages        0.087839
frozen           0.080635
Name: proportion, dtype: float64

In [14]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')

In [15]:
df_products_enriched = pd.merge(
    df_products_departments,
    df_aisles,
    on= 'aisle_id',
    how= 'left'
)

In [16]:
df_products_aisles_check = pd.merge(
    df_products_departments,
    df_aisles,
    on= 'aisle_id',
    how= 'left',
    indicator= True
)
df_products_aisles_check['_merge'].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

In [55]:
df_products.shape
print(df_products_departments.shape)
print(df_products_enriched.shape)

(49693, 6)
(49693, 7)

In [59]:
# Homework P2: Questions unlocked after enriching products
# How many products belong to each department?
df_products_departments['department'].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [60]:
# How many products belong to each aisle?
df_products_enriched['aisle'].value_counts()

aisle
missing                         1258
candy chocolate                 1246
ice cream ice                   1091
vitamins supplements            1038
yogurt                          1026
                                ...
frozen juice                      47
baby accessories                  44
packaged produce                  32
bulk grains rice dried goods      26
bulk dried fruits vegetables      12
Name: count, Length: 134, dtype: int64

In [65]:
# Which aisles are most populated?
df_products_enriched['aisle'].value_counts().head(3).index

Index(['missing', 'candy chocolate', 'ice cream ice'], dtype='str', name='aisle')

In [15]:
# Which departments span the widest variety of products?
df_products_enriched['department'].value_counts().head()

department
personal care    6565
snacks           6264
pantry           5371
beverages        4365
frozen           4007
Name: count, dtype: int64

In [19]:
# How are departments and aisles related?
pd.crosstab(
    df_products_enriched["department"],
    df_products_enriched["aisle"]
)

aisle,air fresheners candles,asian foods,baby accessories,baby bath body care,baby food formula,bakery desserts,baking ingredients,baking supplies decor,beauty,beers coolers,...,spreads,tea,tofu meat alternatives,tortillas flat bread,trail mix snack mix,trash bags liners,vitamins supplements,water seltzer sparkling water,white wines,yogurt
department,,,,,,,,,,,,,,,,,,,,,
alcohol,0,0,0,0,0,0,0,0,0,387,...,0,0,0,0,0,0,0,0,147,0
babies,0,0,44,132,718,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bakery,0,0,0,0,0,297,0,0,0,0,...,0,0,0,241,0,0,0,0,0,0
beverages,0,0,0,0,0,0,0,0,0,0,...,0,894,0,0,0,0,0,344,0,0
breakfast,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bulk,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
canned goods,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dairy eggs,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1026
deli,0,0,0,0,0,0,0,0,0,0,...,0,0,159,0,0,0,0,0,0,0
dry goods pasta,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
frozen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
household,355,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,112,0,0,0,0
international,0,605,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
meat seafood,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
missing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
other,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pantry,0,0,0,0,0,0,623,290,0,0,...,493,0,0,0,0,0,0,0,0,0
personal care,0,0,0,0,0,0,0,0,178,0,...,0,0,0,0,0,0,1038,0,0,0
pets,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
produce,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
snacks,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,69,0,0,0,0,0

In [20]:
# Inner Join
pd.merge (
    df_products,
    df_departments,
    on= 'department_id',
    how= 'inner'
).head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks
1,2,All-Seasons Salt,104,13,9.3,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry

In [21]:
# Left Join
pd.merge (
    df_products,
    df_departments,
    on= 'department_id',
    how= 'left'
).head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks
1,2,All-Seasons Salt,104,13,9.3,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry

In [22]:
# Outer Join
pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="outer"
).head()

,product_id,product_name,aisle_id,department_id,prices,department
0,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen
1,8,Cut Russet Potatoes Steam N' Mash,116,1,1.1,frozen
2,12,Chocolate Fudge Layer Cake,119,1,9.4,frozen
3,18,Pizza for One Suprema Frozen Pizza,79,1,10.6,frozen
4,30,"Three Cheese Ziti, Marinara with Meatballs",38,1,13.8,frozen

In [23]:
df_orders_train = df_orders[df_orders['eval_set'] == 'train']
df_orders_train.drop(columns=['eval_set'], inplace= True)
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')

In [24]:
df_train_transactions = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left"
)

df_train_transactions.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1187899,1,11,4,8,14.0,196,1,1
1,1187899,1,11,4,8,14.0,25133,2,1
2,1187899,1,11,4,8,14.0,38928,3,1
3,1187899,1,11,4,8,14.0,26405,4,1
4,1187899,1,11,4,8,14.0,39657,5,1

In [25]:
df_train_transactions_check = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left",
    indicator=True
)

df_train_transactions_check.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,1187899,1,11,4,8,14.0,196,1,1,both
1,1187899,1,11,4,8,14.0,25133,2,1,both
2,1187899,1,11,4,8,14.0,38928,3,1,both
3,1187899,1,11,4,8,14.0,26405,4,1,both
4,1187899,1,11,4,8,14.0,39657,5,1,both

In [ ]:
# շատ կարևոր checkա

df_train_transactions_check[
    df_train_transactions_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [order_id, user_id, order_number, order_dow, order_hour_of_day, days_since_prior_order, product_id, add_to_cart_order, reordered, _merge]
Index: []

In [26]:
df_orders.shape
df_orders_products_train.shape
df_train_transactions.shape

(1384617, 9)

In [27]:
df_train_transactions.columns

Index(['order_id', 'user_id', 'order_number', 'order_dow', 'order_hour_of_day',
       'days_since_prior_order', 'product_id', 'add_to_cart_order',
       'reordered'],
      dtype='str')

In [89]:
# Homework P3: Questions unlocked after this merge
# How many products are included in each order?
df_train_transactions.groupby('order_id').size().head()

order_id
1      8
36     8
38     9
96     7
98    49
dtype: int64

In [ ]:
df_train_transactions.groupby('order_id').size()

count    131209.000000
mean         10.552759
std           7.932847
min           1.000000
25%           5.000000
50%           9.000000
75%          14.000000
max          80.000000
dtype: float64

In [26]:
# What is the typical basket size?
typ_bsk_size = df_train_transactions.groupby('order_id').size().mean()
typ_bsk_size

np.float64(10.552759338155157)

In [51]:
# Are larger baskets more common on specific days?
bsk_sizes = df_train_transactions.groupby(['order_id', 'order_dow']).size().reset_index(name= 'size')
bsk_sizes

        order_id  order_dow  size
0              1          4     8
1             36          6     8
2             38          6     9
3             96          6     7
4             98          3    49
...          ...        ...   ...
131204   3421049          1     6
131205   3421056          2     5
131206   3421058          3     8
131207   3421063          0     4
131208   3421070          6     3

[131209 rows x 3 columns]

In [52]:
avg_size = bsk_sizes.groupby('order_dow')['order_id'].mean()
avg_size

order_dow
0    1.704552e+06
1    1.693593e+06
2    1.709383e+06
3    1.697767e+06
4    1.705797e+06
5    1.700362e+06
6    1.716793e+06
Name: order_id, dtype: float64

In [41]:
# Are reordered items more common at certain times of day?
reorder_by_hour = df_train_transactions.groupby('order_hour_of_day')['reordered'].mean()
reorder_by_hour

order_hour_of_day
0     0.571177
1     0.579453
2     0.579665
3     0.581624
4     0.598108
5     0.622823
6     0.650629
7     0.649496
8     0.643353
9     0.623263
10    0.606378
11    0.594423
12    0.587193
13    0.589533
14    0.592201
15    0.583384
16    0.588795
17    0.592177
18    0.584747
19    0.590529
20    0.596921
21    0.607934
22    0.604195
23    0.589979
Name: reordered, dtype: float64

In [55]:
# Does basket size differ by order sequence?
basket_sizes_seq = df_train_transactions.groupby(["order_id", "order_number"]).size().reset_index(name="bsk_size")
avg_by_seq = basket_sizes_seq.groupby("order_number")["bsk_size"].mean()

print(avg_by_seq.head(10))

order_number
4      9.796209
5      9.932310
6     10.189417
7     10.273241
8     10.282044
9     10.563350
10    10.486938
11    10.522769
12    10.745843
13    10.790459
Name: bsk_size, dtype: float64

In [44]:
df_train_transactions.columns

Index(['order_id', 'user_id', 'order_number', 'order_dow', 'order_hour_of_day',
       'days_since_prior_order', 'product_id', 'add_to_cart_order',
       'reordered'],
      dtype='str')

In [28]:
# final merge
df_train_analytic = pd.merge(
    df_train_transactions,
    df_products_enriched,
    on="product_id",
    how="left"
)

df_train_analytic.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle
0,1187899,1,11,4,8,14.0,196,1,1,Soda,77.0,7.0,9.0,beverages,soft drinks
1,1187899,1,11,4,8,14.0,25133,2,1,Organic String Cheese,21.0,16.0,8.6,dairy eggs,packaged cheese
2,1187899,1,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,120.0,16.0,12.6,dairy eggs,yogurt
3,1187899,1,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,household,paper goods
4,1187899,1,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,45.0,19.0,6.8,snacks,candy chocolate

In [29]:
df_train_analytic_check = pd.merge(
    df_train_transactions,
    df_products_enriched,
    on="product_id",
    how="left",
    indicator=True
)

df_train_analytic_check["_merge"].value_counts()

_merge
both          1384618
left_only          88
right_only          0
Name: count, dtype: int64

In [62]:
# Homework P4 Questions unlocked after the final merge
# Which products are purchased most often?
df_train_analytic["product_name"].value_counts().head(10)

product_name
Banana                    18726
Bag of Organic Bananas    15480
Organic Strawberries      10894
Organic Baby Spinach       9784
Large Lemon                8135
Organic Avocado            7409
Organic Hass Avocado       7293
Strawberries               6494
Limes                      6033
Organic Raspberries        5546
Name: count, dtype: int64

In [63]:
# Which departments dominate train orders?
df_train_analytic["department"].value_counts()

department
produce            409087
dairy eggs         217051
snacks             118862
beverages          113962
frozen             100426
pantry              81242
bakery              48394
canned goods        46799
deli                44291
dry goods pasta     38713
household           35986
meat seafood        30307
breakfast           29552
personal care       21599
babies              14941
international       11902
missing              8251
alcohol              5602
pets                 4497
other                1795
bulk                 1359
Name: count, dtype: int64

In [65]:
# Which aisles dominate train orders?
df_train_analytic['aisle'].value_counts().head(10)

aisle
fresh vegetables                 150609
fresh fruits                     150473
packaged vegetables fruits        78493
yogurt                            55240
packaged cheese                   41699
water seltzer sparkling water     36617
milk                              32644
chips pretzels                    31269
soy lactosefree                   26240
bread                             23635
Name: count, dtype: int64

In [66]:
# Which departments have the highest reorder rates?
df_train_analytic.groupby("department")["reordered"].mean().sort_values(ascending=False)

department
dairy eggs         0.674966
produce            0.664617
beverages          0.658132
bakery             0.634211
pets               0.630198
deli               0.617891
alcohol            0.606748
meat seafood       0.590854
snacks             0.581363
bulk               0.578366
breakfast          0.571806
frozen             0.559297
babies             0.541062
dry goods pasta    0.487821
canned goods       0.486805
household          0.427166
other              0.388301
missing            0.381530
international      0.379936
pantry             0.363088
personal care      0.337516
Name: reordered, dtype: float64

In [74]:
# Which aisles appear most often in large baskets?

bsk_counts = df_train_analytic.groupby("order_id").size()
large_order_ids = bsk_counts[bsk_counts > 20].index
# 20ից ավել ապրանք ունեցողների IDները

In [75]:
df_large_baskets_only = df_train_analytic[df_train_analytic["order_id"].isin(large_order_ids)]

top_aisles = df_large_baskets_only["aisle"].value_counts().head(3)
top_aisles

aisle
fresh vegetables              46408
fresh fruits                  40132
packaged vegetables fruits    22526
Name: count, dtype: int64

In [30]:
# At what times are certain departments purchased more frequently?
pd.crosstab(
    df_train_analytic["order_dow"],
    df_train_analytic["reordered"],
    normalize="index"
).style.format("{:.1%}")

In [78]:
# At what times are certain departments purchased more frequently?
pd.crosstab(
    df_train_analytic["order_dow"],
    df_train_analytic["reordered"],
    normalize="index"
).style.format("{:.1%}")

In [41]:
# MERGING 2 MORE CSVS WITH FINAL_ANALYTIC
df_customers = pd.read_csv('../data/raw/customers.csv')
df_states = pd.read_csv('../data/raw/states.csv')

In [43]:
df_customers.head()
df_states.head()

           state     region     division
0    Connecticut  Northeast  New England
1          Maine  Northeast  New England
2  Massachusetts  Northeast  New England
3  New Hampshire  Northeast  New England
4   Rhode Island  Northeast  New England

In [35]:
df_train_analytic.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle
0,1187899,1,11,4,8,14.0,196,1,1,Soda,77.0,7.0,9.0,beverages,soft drinks
1,1187899,1,11,4,8,14.0,25133,2,1,Organic String Cheese,21.0,16.0,8.6,dairy eggs,packaged cheese
2,1187899,1,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,120.0,16.0,12.6,dairy eggs,yogurt
3,1187899,1,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,household,paper goods
4,1187899,1,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,45.0,19.0,6.8,snacks,candy chocolate

In [ ]:
df_merged_with_customers = pd.merge(
    df_train_analytic,
    df_customers,
    on='user_id',
    how= 'left'
    )
df_merged_with_customers.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,aisle,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,1187899,1,11,4,8,14.0,196,1,1,Soda,...,soft drinks,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
1,1187899,1,11,4,8,14.0,25133,2,1,Organic String Cheese,...,packaged cheese,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
2,1187899,1,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,...,yogurt,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
3,1187899,1,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,...,paper goods,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
4,1187899,1,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,...,candy chocolate,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423

In [50]:
df_merged_with_states = pd.merge(
    df_merged_with_customers,
    df_states,
    on= 'state',
    how= 'left'
)
df_merged_with_states.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,1,11,4,8,14.0,196,1,1,Soda,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,1,11,4,8,14.0,25133,2,1,Organic String Cheese,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,1,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,1,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,1,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [ ]:
# անունը փոխենք, որ կարողանանք merge անել
df_merged_with_customers = df_merged_with_customers.rename(columns= {'STATE': 'state'})

In [51]:
df_merged_with_states.to_csv('../data/processed/merged.csv')