In [4]:
import pandas as pd
df_scores = pd.DataFrame({
    "student":  ["Anna","Ben", "Chris", "Diana", "Eva"],
    "score":  [95, 78, 61, 43, 88]
})
df_scores

  student  score
0    Anna     95
1     Ben     78
2   Chris     61
3   Diana     43
4     Eva     88

In [6]:
def score_label (score):
    if score >= 90:
        return "Excellent"
    elif score >= 70:
        return "Good"
    elif score >= 50:
        return "Pass"
    else:
        return "Fail"
score_label(86)

'Good'

### option 1

In [7]:
df_scores["score_label"] = df_scores["score"].apply(score_label)

In [8]:
df_scores

  student  score score_label
0    Anna     95   Excellent
1     Ben     78        Good
2   Chris     61        Pass
3   Diana     43        Fail
4     Eva     88        Good

### option 2

In [10]:
df_scores["score_label"] = [score_label(i) for i in df_scores["score"]]
df_scores

  student  score score_label
0    Anna     95   Excellent
1     Ben     78        Good
2   Chris     61        Pass
3   Diana     43        Fail
4     Eva     88        Good

In [ ]:
def classify_price(price, low = 5, high = 15):
    if price <= low:
        return "Low-range product"
    elif price <= high:
        return "Mid-range product"
    else:
        return "High-range product"
classify_price(9)