In [66]:
from datetime import datetime, date, timedelta
import pandas as pd

In [ ]:
# Task 1/1

my_date = date(2025, 3, 15)
print(f"Full Value:{my_date}|The Year:{my_date.year}|The Month:{my_date.month}|The Day:{my_date.day}")

Full Value:2025-03-15|The Year:2025|The Month:3|The Day:15

In [ ]:
# Task 1/2

meeting_time = datetime(2025, 10, 8, 16, 45, 30)
print(f"""The Year:{meeting_time.year}, 
The Month:{meeting_time.month}, 
The Day:{meeting_time.day}, 
The Hour:{meeting_time.hour}, 
The Minuutes:{meeting_time.minute}, 
The Seconds:{meeting_time.second}""")

The Year:2025,
The Month:10,
The Day:8,
The Hour:16,
The Minuutes:45,
The Seconds:30

In [ ]:
# Task 1/3

d1 = meeting_time.strftime("%Y-%m-%d")
d2 = meeting_time.strftime("%d/%m/%Y")
d3 = meeting_time.strftime("%B %d, %Y")
print(d1)
print(d2)
print(d3)

2025-10-08
08/10/2025
October 08, 2025

In [48]:
# Task 1/4

date_str = "2025-12-31"
to_date = datetime.strptime(date_str, "%Y-%m-%d")
print(f"Converted to date: {to_date}")

Converted to date: 2025-12-31 00:00:00

In [52]:
# Task 1/5

start = date(2025, 1, 10)
end = date(2025, 2, 5)
delta = end - start
print(delta.days)

26

In [65]:
# Task 1/6

start = date(2025, 1, 10)
print(f"Start: {start}")
after_10_days = start + timedelta(days = 10)
print(f"After 10 days: {after_10_days}")

before_14_days = start - timedelta(days = 14)
print(f"Before 14 days: {before_14_days}")

after_3_weeks = start + timedelta(weeks = 3)
print(f"After 3 weeks: {after_3_weeks}")

my_datetime = datetime(2025, 1, 10, 0, 0, 0)

after_5_hours = my_datetime + timedelta(hours = 5)
print(f"The datetime after 5 hours: {after_5_hours}")

after_20_minutes = after_5_hours + timedelta(minutes = 20)
print(f"The datetime after 20 minutes: {after_20_minutes}")

after_45_seconds = after_20_minutes + timedelta(seconds = 45)
print(f"The datetime after 45 seconds: {after_45_seconds}")

Start: 2025-01-10
After 10 days: 2025-01-20
Before 14 days: 2024-12-27
After 3 weeks: 2025-01-31
The datetime after 5 hours: 2025-01-10 05:00:00
The datetime after 20 minutes: 2025-01-10 05:20:00
The datetime after 45 seconds: 2025-01-10 05:20:45

In [69]:
# Task 2/1

my_df = pd.DataFrame(
    {
        "customer_id" : [1, 2, 3, 4, 5],
        "signup_date" : ["2024-01-10", "2024-02-05", "2024-03-12", "2024-04-01", "2024-05-20"],
        "last_purchase" : ["2024-02-15", "2024-03-01", "2024-03-28", "2024-05-10", "2024-06-25"]
    }
)

print(my_df)

   customer_id signup_date last_purchase
0            1  2024-01-10    2024-02-15
1            2  2024-02-05    2024-03-01
2            3  2024-03-12    2024-03-28
3            4  2024-04-01    2024-05-10
4            5  2024-05-20    2024-06-25

In [74]:
my_df["signup_date"] = pd.to_datetime(my_df["signup_date"])
my_df["last_purchase"] = pd.to_datetime(my_df["last_purchase"])

In [75]:
my_df.dtypes

customer_id               int64
signup_date      datetime64[us]
last_purchase    datetime64[us]
dtype: object

In [94]:
# Task 2/7

my_df["signup_year"] = my_df["signup_date"].dt.year
my_df["signup_month"] = my_df["signup_date"].dt.month
my_df["signup_day"] = my_df["signup_date"].dt.day
my_df["signup_quarter"] = my_df["signup_date"].dt.quarter
my_df["signup_month_name"] = my_df["signup_date"].dt.month_name()
my_df["signup_day_name"] = my_df["signup_date"].dt.day_name()
print(my_df.head())
print(my_df.dtypes)

   customer_id signup_date last_purchase  signup_year  signup_month  \
0            1  2024-01-10    2024-02-15         2024             1
1            2  2024-02-05    2024-03-01         2024             2
2            3  2024-03-12    2024-03-28         2024             3
3            4  2024-04-01    2024-05-10         2024             4
4            5  2024-05-20    2024-06-25         2024             5

   signup_day  signup_quarter signup_month_name signup_day_name
0          10               1           January       Wednesday
1           5               1          February          Monday
2          12               1             March         Tuesday
3           1               2             April          Monday
4          20               2               May          Monday
customer_id                   int64
signup_date          datetime64[us]
last_purchase        datetime64[us]
signup_year                   int32
signup_month                  int32
signup_day                    int32
signup_quarter                int32
signup_month_name               str
signup_day_name                 str
dtype: object

In [ ]:
# Task 2/8

my_df["signup_dow"] = my_df["signup_date"].dt.day_of_week
my_df["is_weekend"] = my_df["signup_date"].dt.day_of_week.isin([5, 6]) # becasue in pandas 5 - saturday, 6 - sunday
print(my_df.head())

   customer_id signup_date last_purchase  signup_year  signup_month  \
0            1  2024-01-10    2024-02-15         2024             1
1            2  2024-02-05    2024-03-01         2024             2
2            3  2024-03-12    2024-03-28         2024             3
3            4  2024-04-01    2024-05-10         2024             4
4            5  2024-05-20    2024-06-25         2024             5

   signup_day  signup_quarter signup_month_name signup_day_name  signup_dow  \
0          10               1           January       Wednesday           2
1           5               1          February          Monday           0
2          12               1             March         Tuesday           1
3           1               2             April          Monday           0
4          20               2               May          Monday           0

   is_weekend
0       False
1       False
2       False
3       False
4       False

In [104]:
# Task 2/9

my_df["days_between_signup_and_purchase"] = (my_df["last_purchase"] - my_df["signup_date"]).dt.days
print(my_df.head())
print(my_df.dtypes)

   customer_id signup_date last_purchase  signup_year  signup_month  \
0            1  2024-01-10    2024-02-15         2024             1
1            2  2024-02-05    2024-03-01         2024             2
2            3  2024-03-12    2024-03-28         2024             3
3            4  2024-04-01    2024-05-10         2024             4
4            5  2024-05-20    2024-06-25         2024             5

   signup_day  signup_quarter signup_month_name signup_day_name  signup_dow  \
0          10               1           January       Wednesday           2
1           5               1          February          Monday           0
2          12               1             March         Tuesday           1
3           1               2             April          Monday           0
4          20               2               May          Monday           0

   is_weekend  days_between_signup_and_purchase
0       False                                36
1       False                                25
2       False                                16
3       False                                39
4       False                                36
customer_id                                  int64
signup_date                         datetime64[us]
last_purchase                       datetime64[us]
signup_year                                  int32
signup_month                                 int32
signup_day                                   int32
signup_quarter                               int32
signup_month_name                              str
signup_day_name                                str
signup_dow                                   int32
is_weekend                                    bool
days_between_signup_and_purchase             int64
dtype: object

In [ ]:
# Task 2/10

my_df

# customers who signed up after "2024-03-01"
my_df[my_df["signup_date"] > "2024-03-01"]
# customers who signed up in March
my_df[my_df["signup_date"].dt.month == 3]
# customers who signed up in 2024
my_df[my_df["signup_date"].dt.year == 2024]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
0,1,2024-01-10,2024-02-15,2024,1,10,1,January,Wednesday,2,False,36
1,2,2024-02-05,2024-03-01,2024,2,5,1,February,Monday,0,False,25
2,3,2024-03-12,2024-03-28,2024,3,12,1,March,Tuesday,1,False,16
3,4,2024-04-01,2024-05-10,2024,4,1,2,April,Monday,0,False,39
4,5,2024-05-20,2024-06-25,2024,5,20,2,May,Monday,0,False,36

In [119]:
# Task 2/11

my_df.sort_values(by= "signup_date", ascending = False)

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
4,5,2024-05-20,2024-06-25,2024,5,20,2,May,Monday,0,False,36
3,4,2024-04-01,2024-05-10,2024,4,1,2,April,Monday,0,False,39
2,3,2024-03-12,2024-03-28,2024,3,12,1,March,Tuesday,1,False,16
1,2,2024-02-05,2024-03-01,2024,2,5,1,February,Monday,0,False,25
0,1,2024-01-10,2024-02-15,2024,1,10,1,January,Wednesday,2,False,36

In [133]:
# Task 2/12

date_list = pd.date_range(start = "2024-07-01", periods = 10, freq = 'D')
date_list
my_df["date_list"] = date_list[0:5]
print(my_df)

   customer_id signup_date last_purchase  signup_year  signup_month  \
0            1  2024-01-10    2024-02-15         2024             1
1            2  2024-02-05    2024-03-01         2024             2
2            3  2024-03-12    2024-03-28         2024             3
3            4  2024-04-01    2024-05-10         2024             4
4            5  2024-05-20    2024-06-25         2024             5

   signup_day  signup_quarter signup_month_name signup_day_name  signup_dow  \
0          10               1           January       Wednesday           2
1           5               1          February          Monday           0
2          12               1             March         Tuesday           1
3           1               2             April          Monday           0
4          20               2               May          Monday           0

   is_weekend  days_between_signup_and_purchase  date_list
0       False                                36 2024-07-01
1       False                                25 2024-07-02
2       False                                16 2024-07-03
3       False                                39 2024-07-04
4       False                                36 2024-07-05

In [136]:
# Task 2/13

date_list2 = pd.date_range(start = "2024-01-01", periods = 12, freq = "ME")
my_df["date_list2"] = date_list2[0:5]
print(my_df)

   customer_id signup_date last_purchase  signup_year  signup_month  \
0            1  2024-01-10    2024-02-15         2024             1
1            2  2024-02-05    2024-03-01         2024             2
2            3  2024-03-12    2024-03-28         2024             3
3            4  2024-04-01    2024-05-10         2024             4
4            5  2024-05-20    2024-06-25         2024             5

   signup_day  signup_quarter signup_month_name signup_day_name  signup_dow  \
0          10               1           January       Wednesday           2
1           5               1          February          Monday           0
2          12               1             March         Tuesday           1
3           1               2             April          Monday           0
4          20               2               May          Monday           0

   is_weekend  days_between_signup_and_purchase  date_list date_list2
0       False                                36 2024-07-01 2024-01-31
1       False                                25 2024-07-02 2024-02-29
2       False                                16 2024-07-03 2024-03-31
3       False                                39 2024-07-04 2024-04-30
4       False                                36 2024-07-05 2024-05-31

In [139]:
# Task 2/14

new_df = pd.DataFrame(
    {
    "date": pd.date_range(start = "2024-01-01", periods = 15, freq = 'D'),
    "sales": [20, 40, 50, 40, 80, 90, 30, 80, 70, 90, 50, 20, 40, 70, 60]  
    }
)
print(new_df)

         date  sales
0  2024-01-01     20
1  2024-01-02     40
2  2024-01-03     50
3  2024-01-04     40
4  2024-01-05     80
5  2024-01-06     90
6  2024-01-07     30
7  2024-01-08     80
8  2024-01-09     70
9  2024-01-10     90
10 2024-01-11     50
11 2024-01-12     20
12 2024-01-13     40
13 2024-01-14     70
14 2024-01-15     60

In [ ]:
new_df["year"] = new_df["date"].dt.year
new_df["month"] = new_df["date"].dt.month
new_df["day"] = new_df["date"].dt.day
new_df["day_name"] = new_df["date"].dt.day_name()
new_df["dow"] = new_df["date"].dt.day_of_week
new_df["is_weekand"] = new_df["date"].dt.day_of_week.isin([5, 6]).astype(int)

print(new_df)
print(new_df.dtypes)

         date  sales  year  month  day   day_name  dow  is_weekand
0  2024-01-01     20  2024      1    1     Monday    0           0
1  2024-01-02     40  2024      1    2    Tuesday    1           0
2  2024-01-03     50  2024      1    3  Wednesday    2           0
3  2024-01-04     40  2024      1    4   Thursday    3           0
4  2024-01-05     80  2024      1    5     Friday    4           0
5  2024-01-06     90  2024      1    6   Saturday    5           1
6  2024-01-07     30  2024      1    7     Sunday    6           1
7  2024-01-08     80  2024      1    8     Monday    0           0
8  2024-01-09     70  2024      1    9    Tuesday    1           0
9  2024-01-10     90  2024      1   10  Wednesday    2           0
10 2024-01-11     50  2024      1   11   Thursday    3           0
11 2024-01-12     20  2024      1   12     Friday    4           0
12 2024-01-13     40  2024      1   13   Saturday    5           1
13 2024-01-14     70  2024      1   14     Sunday    6           1
14 2024-01-15     60  2024      1   15     Monday    0           0
date          datetime64[us]
sales                  int64
year                   int32
month                  int32
day                    int32
day_name                 str
dow                    int32
is_weekand             int64
dtype: object

In [168]:
# Task 2/15


some_date = pd.Timestamp("2024-08-18")
print(f"Original date: {some_date}")

month_period = some_date.to_period("M")

beginning = month_period.start_time
end = month_period.end_time
print(f"Beginning of month: {beginning}")
print(f"End of month: {end}")

beginning_as_date = beginning.date()
end_as_date = end.date()

print(f"Beginning of month as date only: {beginning_as_date}")
print(f"End of month as date only: {end_as_date}")

Original date: 2024-08-18 00:00:00
Beginning of month: 2024-08-01 00:00:00
End of month: 2024-08-31 23:59:59.999999
Beginning of month as date only: 2024-08-01
End of month as date only: 2024-08-31

In [ ]:
# Task 2/16

my_df["month_start"] = my_df["signup_date"].dt.to_period("M").dt.start_time
my_df["month_end"] = my_df["signup_date"].dt.to_period("M").dt.end_time

print(my_df[["signup_date", "month_start", "month_end"]].head())

my_df["month_start"] = my_df["month_start"].dt.date # AS DATE
my_df["month_end"] = my_df["month_end"].dt.date # AS DATE

print(my_df[["signup_date", "month_start", "month_end"]].head())

  signup_date month_start                  month_end
0  2024-01-10  2024-01-01 2024-01-31 23:59:59.999999
1  2024-02-05  2024-02-01 2024-02-29 23:59:59.999999
2  2024-03-12  2024-03-01 2024-03-31 23:59:59.999999
3  2024-04-01  2024-04-01 2024-04-30 23:59:59.999999
4  2024-05-20  2024-05-01 2024-05-31 23:59:59.999999
  signup_date month_start   month_end
0  2024-01-10  2024-01-01  2024-01-31
1  2024-02-05  2024-02-01  2024-02-29
2  2024-03-12  2024-03-01  2024-03-31
3  2024-04-01  2024-04-01  2024-04-30
4  2024-05-20  2024-05-01  2024-05-31