# Dates

In [ ]:
from datetime import datetime, date, timedelta

In [4]:
my_date = date(2026, 3, 24)

In [6]:
type(my_date)

datetime.date

In [11]:
my_time = datetime(year = 2025, month = 3, day = 24)
my_time

datetime.datetime(2025, 3, 24, 0, 0)

In [13]:
start_date = my_date
end_date = date(2026, 4, 4)

In [15]:
delta = end_date - start_date
delta

datetime.timedelta(days=11)

# Date with Pandas

In [1]:
import pandas as pd

In [ ]:
df_dates = pd.DataFrame(
    {"customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]}
)
df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [12]:
df_dates['signup_date'] = pd.to_datetime(df_dates['signup_date'])
df_dates['last_purchase'] = pd.to_datetime(df_dates['last_purchase'])
df_dates.dtypes

customer_id               int64
signup_date      datetime64[us]
last_purchase    datetime64[us]
dtype: object

In [13]:
df_dates["signup_year"] = df_dates["signup_date"].dt.year
df_dates["signup_month"] = df_dates["signup_date"].dt.month
df_dates["signup_day"] = df_dates["signup_date"].dt.day

df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day
0,101,2024-01-15,2024-06-01,2024,1,15
1,102,2024-02-20,2024-06-15,2024,2,20
2,103,2024-03-05,2024-07-01,2024,3,5
3,104,2024-03-18,2024-07-08,2024,3,18
4,105,2024-04-10,2024-07-12,2024,4,10

In [14]:
df_dates["signup_month_name"] = df_dates["signup_date"].dt.month_name()
df_dates["signup_day_name"] = df_dates["signup_date"].dt.day_name()

df_dates[["signup_date", "signup_month_name", "signup_day_name"]]

  signup_date signup_month_name signup_day_name
0  2024-01-15           January          Monday
1  2024-02-20          February         Tuesday
2  2024-03-05             March         Tuesday
3  2024-03-18             March          Monday
4  2024-04-10             April       Wednesday

In [15]:
df_dates["signup_quarter"] = df_dates["signup_date"].dt.quarter
df_dates[["signup_date", "signup_quarter"]]

  signup_date  signup_quarter
0  2024-01-15               1
1  2024-02-20               1
2  2024-03-05               1
3  2024-03-18               1
4  2024-04-10               2

In [16]:
df_dates["signup_dow"] = df_dates["signup_date"].dt.dayofweek
df_dates[["signup_date", "signup_dow"]]

  signup_date  signup_dow
0  2024-01-15           0
1  2024-02-20           1
2  2024-03-05           1
3  2024-03-18           0
4  2024-04-10           2

In [20]:
df_dates["is_weekend"] = (df_dates["signup_date"].dt.dayofweek >= 5).astype(int)
df_dates[["signup_date", "signup_dow", "is_weekend"]]

  signup_date  signup_dow  is_weekend
0  2024-01-15           0           0
1  2024-02-20           1           0
2  2024-03-05           1           0
3  2024-03-18           0           0
4  2024-04-10           2           0

In [18]:
df_dates["days_between_signup_and_purchase"] = (
    df_dates["last_purchase"] - df_dates["signup_date"]
).dt.days

df_dates[["signup_date", "last_purchase", "days_between_signup_and_purchase"]]

  signup_date last_purchase  days_between_signup_and_purchase
0  2024-01-15    2024-06-01                               138
1  2024-02-20    2024-06-15                               116
2  2024-03-05    2024-07-01                               118
3  2024-03-18    2024-07-08                               112
4  2024-04-10    2024-07-12                                93

In [23]:
df_dates[df_dates['signup_date'] > '2024-03-01']
df_dates[df_dates['signup_date'].dt.year == 2024]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

In [25]:
df_dates.sort_values('signup_date', ascending = False)

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,1,0,116
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,1,0,0,138

In [2]:
pd.date_range(start = '2024-01-01', periods= 12, freq = 'ME')

DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31'],
              dtype='datetime64[us]', freq='ME')

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)
px.defaults.template = "plotly_white"

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [3]:
px.defaults.template = "plotly_white"

In [4]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum()
)

region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [5]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    text="sales",
    title="Total Sales by Region"
)

fig.update_traces(textposition="outside")
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales"
)

fig.show()

In [6]:
monthly_sales = (
    df_plotly.groupby("month", as_index=False)["sales"]
             .sum()
)

monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [7]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

In [8]:
fig = px.histogram(
    df_plotly,
    x="sales",
    nbins=15,
    title="Distribution of Sales"
)

fig.update_layout(
    xaxis_title="Sales",
    yaxis_title="Count"
)

fig.show()

In [9]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    hover_data=["product", "month_name", "units"],
    title="Customers vs Sales"
)

fig.update_layout(
    xaxis_title="Customers",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()

In [10]:
monthly_region_sales = (
    df_plotly.groupby(["month", "region"], as_index=False)["sales"]
             .sum()
)

monthly_region_sales.head()

       month region  sales
0 2024-01-01   East    217
1 2024-01-01  North    276
2 2024-01-01  South    314
3 2024-02-01   East    273
4 2024-02-01  North    305

In [11]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="region",
    markers=True,
    title="Monthly Sales by Region"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()

In [12]:
region_product_sales = (
    df_plotly.groupby(["region", "product"], as_index=False)["sales"]
             .sum()
)

region_product_sales

  region product  sales
0   East       A    853
1   East       B    706
2  North       A    888
3  North       B    912
4  South       A    958
5  South       B    716

In [13]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product"
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

fig.show()

In [14]:
product_sales = (
    df_plotly.groupby("product", as_index=False)["sales"]
             .sum()
)

product_sales

  product  sales
0       A   2699
1       B   2334

In [15]:
fig = px.pie(
    product_sales,
    names="product",
    values="sales",
    hole=0.5,
    title="Share of Total Sales by Product"
)

fig.update_traces(textinfo="label+percent")

fig.show()

In [16]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region",
    color_discrete_sequence=["#a34e31"]
)

fig.show()

In [19]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales",
    color_discrete_sequence=["crimson"]
)

fig.show()

In [20]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="region",
    markers=True,
    title="Monthly Sales by Region",
    color_discrete_sequence=["#1f77b4", "#ff7f0e", "#2ca02c"]
)

fig.show()

In [21]:
fig = px.histogram(
    df_plotly,
    x="sales",
    nbins=15,
    title="Distribution of Sales",
    color_discrete_sequence=["purple"]
)

fig.show()

In [22]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    title="Customers vs Sales",
    color_discrete_sequence=["darkorange"]
)

fig.show()

In [23]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    title="Customers vs Sales by Region",
    color_discrete_sequence=["#3B6EAD", "#AFC4E8", "#B7C2D1"]
)

fig.show()

In [24]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region"
)

fig.update_traces(marker_color="teal")

fig.show()

In [25]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    title="Monthly Total Sales"
)

fig.update_traces(line_color="red")

fig.show()

In [26]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum()
)

top_region = region_sales.loc[region_sales["sales"].idxmax(), "region"]

region_sales["highlight"] = np.where(
    region_sales["region"] == top_region,
    "Highest Sales",
    "Other Regions"
)

region_sales

  region  sales      highlight
0   East   1559  Other Regions
1  North   1800  Highest Sales
2  South   1674  Other Regions

In [27]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    color="highlight",
    text="sales",
    title="Highlighting Only the Largest Category",
    color_discrete_map={
        "Highest Sales": "#3B6EAD",
        "Other Regions": "#D9D9D9"
    }
)

fig.update_traces(textposition="outside")

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()

In [28]:
product_sales = (
    df_plotly.groupby("product", as_index=False)["sales"]
             .sum()
)

top_product = product_sales.loc[product_sales["sales"].idxmax(), "product"]

product_sales["highlight"] = np.where(
    product_sales["product"] == top_product,
    "Highest Sales",
    "Other Products"
)

product_sales

  product  sales       highlight
0       A   2699   Highest Sales
1       B   2334  Other Products

In [29]:
fig = px.pie(
    product_sales,
    names="product",
    values="sales",
    color="highlight",
    hole=0.5,
    title="Highlighting Only the Largest Category",
    color_discrete_map={
        "Highest Sales": "#3B6EAD",
        "Other Products": "#D9D9D9"
    }
)

fig.update_traces(textinfo="label+percent")

fig.show()

In [30]:
region_totals = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum()
)

top_region = region_totals.loc[region_totals["sales"].idxmin(), "region"]

df_scatter = df_plotly.copy()

df_scatter["highlight"] = np.where(
    df_scatter["region"] == top_region,
    "Highest Sales Region",
    "Other Regions"
)

df_scatter.head()

,month,region,product,sales,customers,units,month_name,highlight
0,2024-01-01,North,A,182,71,38,Jan,Other Regions
1,2024-01-01,North,B,94,80,30,Jan,Other Regions
2,2024-01-01,South,A,182,43,12,Jan,Other Regions
3,2024-01-01,South,B,132,21,33,Jan,Other Regions
4,2024-01-01,East,A,117,21,69,Jan,Highest Sales Region